
package org.dipaz.material.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaterialService", targetNamespace = "http://service.material.dipaz.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MaterialService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.dipaz.material.service.Material
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearMaterial", targetNamespace = "http://service.material.dipaz.org/", className = "org.dipaz.material.service.CrearMaterial")
    @ResponseWrapper(localName = "crearMaterialResponse", targetNamespace = "http://service.material.dipaz.org/", className = "org.dipaz.material.service.CrearMaterialResponse")
    public Material crearMaterial(
        @WebParam(name = "arg0", targetNamespace = "")
        Material arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.dipaz.material.service.Material>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtnerTodas", targetNamespace = "http://service.material.dipaz.org/", className = "org.dipaz.material.service.ObtnerTodas")
    @ResponseWrapper(localName = "obtnerTodasResponse", targetNamespace = "http://service.material.dipaz.org/", className = "org.dipaz.material.service.ObtnerTodasResponse")
    public List<Material> obtnerTodas();

}
